services:
  mt4:
    build: .
    image: angsanch/metatrader4_vnc
    container_name: metatrader4-vnc
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    env_file:
      - .env
      - config.env
  
